### ISSUE TITLE
[BUG] Upgrade to 1.6.5 breaks installation

### ISSUE THREAD

**Issue by hsenechal** [bunkerity/bunkerweb#2745]
### What happened?

After upgrading from 1.6.4, the bunkerweb services are starting correctly, but my letsencrypt wildcard certificate doesn't apply anymore and is replaced by a self-signed one.

Also, while trying to access the UI through local IP (port 80 or 443, same result), i'm stuck on this page looping forever 
<img width="578" height="627" alt="Image" src="https://github.com/user-attachments/assets/ddc54c4a-a260-4120-b762-1376eab3fc08" />

I'm guessing that maybe the upgrade is simply erasing all of my configuration, but i don't understand why
I couldn't find anything relevant in logs

### How to reproduce?

1. Install BunkerWeb <1.6.5 LXC with Proxmox community Helper-Script
2. Upgrade through built-in command "update" inside LXC / or use official procedure to upgrade
3. Access to main UI or any of your services behind it

### Configuration file(s) (yaml or .env)

```YAML

```

### Relevant log output

```shell

```

### BunkerWeb version

1.6.5

### What integration are you using?

Linux

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by travailenligne-vv** [comment]
Can confirm, breaks linux installs, mine was installed manually.
- proxmox lxc, debian 12
- upgraded from script or manually

**Comment by w4tchout** [comment]
I can confirm too. It seems like migration of the database fails. I see multiple errors in the console:

table bw_api_users already exists
table bw_api_permissions already exists
table bw_instances COLUMN https_port already exists
table bw_instances COLUMN https_port already exists etc.

**Comment by TheophileDiot** [comment]
Hi @hsenechal @travailenligne-vv @w4tchout, from what version did you upgrade ?

**Comment by chrweiss123** [comment]
@TheophileDiot 
Same issue, upgraded on ubuntu server LTS 24.04.3 LTS from 1.6.4 to 1.6.5

**Comment by hsenechal** [comment]
@TheophileDiot LXC Debian 12.7 from 1.6.4 to 1.6.5

**Comment by travailenligne-vv** [comment]
> Hi [@hsenechal](https://github.com/hsenechal) [@travailenligne-vv](https://github.com/travailenligne-vv) [@w4tchout](https://github.com/w4tchout), from what version did you upgrade ?

From 1.6.4

**Comment by TheophileDiot** [comment]
Hi again @w4tchout @chrweiss123 @hsenechal @travailenligne-vv , can you try following this steps and it should fix it for you as we hotfixed the version:

1. Softly downgrade the database:
```bash
sqlite3 /var/lib/bunkerweb/db.sqlite3 "UPDATE bw_metadata SET version = '1.6.5-rc2' WHERE id = 1;"
```

2. Download the easy-install script and it's checksum
```bash
wget https://github.com/bunkerity/bunkerweb/releases/download/v1.6.5/install-bunkerweb.sh
wget https://github.com/bunkerity/bunkerweb/releases/download/v1.6.5/install-bunkerweb.sh.sha256
```

3. **⚠ verify the integrity of the script ⚠**
```bash
sha256sum -c install-bunkerweb.sh.sha256
```

4. Run the script
```bash
chmod +x install-bunkerweb.sh
sudo ./install-bunkerweb.sh
```

5. Follow the steps to upgrade and you should be good to go 🙏 

if you're having any issue don't hesitate to reply to this message, mention me and I'll try to help you resolve your situation.

**Comment by hsenechal** [comment]
Thank you @TheophileDiot , i can confirm it works now if you use the easy-install script method

However, to whoever is using the builtin update script from the Proxmox Helper LXC, its currently still broken and is going to need to be fixed too by the maintainer (https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/bunkerweb.sh)

**Comment by TheophileDiot** [comment]
@hsenechal Happy to see that it fixed your issue. New LXC containers should have the fix already implemented 😄

**Comment by Souperrman** [comment]
@TheophileDiot I tried the above solution with no success. My BW 1.6.4 was already running for a few weeks until I upgraded when you guys announced the new version. Did notice the metadata keeps getting reset from rc2 back to rc3 as the scheduler tries to start.

**Comment by w4tchout** [comment]
@TheophileDiot Although the version in bw_metadata is now set to 1.6.5-rc2 in the database (I've confirmed it's set to that), the easy install script still detects version 1.6.5 and doesn't want to upgrade. Anything else I can do?
